facebookincubator/ptp

protocol/management.go
protocol/management_client.go
protocol/management_tlvs.go
protocol/protocol.go
protocol/ptp4l.go
protocol/ptp4l_test.go
protocol/types.go

This diff refactors Management packets to be more generic, and adds `RegisterMgmtTLVDecoder` function to allow extending protocol with custom Management TLVs.
unittests

Management packets refactoring, support dynamic Management TLV extension

---

simpleclient/client.go

Simple fix to work with ipv4
before:
```
abulimov@devvm834 ~/g/s/g/f/p/ptpcheck > sudo ./ptpcheck trace -S 127.0.0.1
INFO[0000] using ClockIdentity 4857dd.fffe.086488, talking to 127.0.0.1 using Two-Step Unicast PTPv2 protocol
No measurements collected
FATA[0000] address 127.0.0.1: no suitable address found
```
after:
```
abulimov@devvm834 ~/g/s/g/f/p/ptpcheck > sudo ./ptpcheck trace -S 127.0.0.1
INFO[0000] using ClockIdentity 4857dd.fffe.086488, talking to 127.0.0.1 using Two-Step Unicast PTPv2 protocol
WARN[0000] Failed to enable hardware timestamps on port 319, falling back to software timestamps
INFO[0000] client -> SIGNALING (for ANNOUNCE, seq=0)
```

Fix ptpcheck trace with IPv4

---

protocol/timestamp.go
protocol/timestamp_test.go

On 32bit arch the Timespec structure has different size (2x 32bit ints vs 2x64bit ints), so had to fix the test data and the code.
```
abulimov@devvm834 ~/g/s/g/f/ptp > GOARCH=386 go test github.com/facebookincubator/ptp/...
?       github.com/facebookincubator/ptp/phc    [no test files]
ok      github.com/facebookincubator/ptp/protocol       (cached)
?       github.com/facebookincubator/ptp/pshark [no test files]
?       github.com/facebookincubator/ptp/ptp4u  [no test files]
ok      github.com/facebookincubator/ptp/ptp4u/server   (cached)
ok      github.com/facebookincubator/ptp/ptp4u/stats    (cached)
?       github.com/facebookincubator/ptp/ptpcheck       [no test files]
?       github.com/facebookincubator/ptp/ptpcheck/checker       [no test files]
? …
```

Fix tests on 32bit arch, fixes #2

---

.circleci/config.yml
go.mod
protocol/management.go
protocol/protocol.go
protocol/timestamp.go
protocol/timestamp_test.go
protocol/unicast.go
ptp4u/main.go
ptp4u/server/config.go
ptp4u/server/server.go
ptp4u/server/server_test.go
ptp4u/server/subscription.go
ptp4u/server/subscription_test.go
ptp4u/server/worker.go
ptp4u/server/worker_test.go
ptp4u/stats/json.go
ptp4u/stats/json_test.go
ptp4u/stats/stats.go
ptp4u/stats/stats_test.go
simpleclient/client.go

* bump go to 1.16
* **protocol**: Provide allocation-free `BytesTo` function in ptp protocol that writes packet in binary form to provided io.Writer
* **protocol**: Expose `ConnFd`, avoid getting connection descriptor on every call of `ReadTXtimestamp`
* **protocol**: Versions of `ReadTXtimestamp` and `ReadPacketWithRXTimestamp` that allow providing buffers that could be later reused
* **ptp4u**: fixed leaking Timers in SubscriptionClient, simpler approach to expiration
* **ptp4u**: switched to reusable buffers and `BytesTo` + `ReadTXtimestampBuf` to avoid allocations when sending out packets
* **ptp4u**: cache of packet structs in sendWorkers
* **ptp4u**: single queue for sendWorkers
* **ptp4u**: stats updates for single queue
Unittests work, extensive internal testing of ptp4u under …

Optimize memory allocations in ptp4u

---

protocol/protocol.go
protocol/protocol_test.go
protocol/types.go
protocol/unicast.go
protocol/unicast_test.go
ptp4u/server/worker.go

Ditch `binary.Write/Read` in favour of manual reading/writing.
Wrote benchmarks, they show that using `binary.Write/Read` is quite inefficient (allocations, reflection), so we have to do the dirty work ourselves.
unittests, benchmarks:
```
BenchmarkReadSyncDelay-24       62649116                18.37 ns/op            0 B/op          0 allocs/op
BenchmarkWriteSync-24           47009586                26.03 ns/op            0 B/op          0 allocs/op
BenchmarkWriteFollowup-24       47982136                25.58 ns/op            0 B/op          0 allocs/op
BenchmarkWriteSignaling-24      20271586                49.71 ns/op            0 B/op          0 allocs/op
BenchmarkReadSignaling-24        4867161               210.9 ns/op           103 B/op          1 allocs/op
```

Zero-allocation Marshalling and Unmarshalling in hot paths of protocol

---

protocol/timestamp.go
protocol/timestamp_test.go
ptp4u/server/server.go
ptp4u/server/server_test.go
ptp4u/server/subscription.go
ptp4u/server/subscription_test.go
ptp4u/server/worker.go
ptp4u/server/worker_test.go
simpleclient/client.go

UDP [WriteTo](https://github.com/golang/go/blob/658b5e66ecbc41a49e6fb5aa63c5d9c804cf305f/src/net/udpsock_posix.go#L79) is extremely inefficient. For every WriteTo it converts IP to the socket address with very many allocations.
```
$ go tool pprof -alloc_space ~/heap.out
File: ptp4u
Build ID: ddaae6815deb530f329ccdb36491b720
Type: alloc_space
Time: Jul 29, 2021 at 1:52pm (PDT)
Duration: 1mins, Total samples = 15.61GB
(pprof) top
Showing nodes accounting for 13252.52MB, 82.90% of 15985.72MB total
Dropped 22 nodes (cum <= 79.93MB)
Showing top 10 nodes out of 32
flat  flat%   sum%        cum   cum%
2229.77MB 13.95% 13.95%  4305.87MB 26.94%  github.com/facebookincubator/ptp/protocol.ReadPacketWithRXTimestamp
1949.12MB …
```

Improve allocations by switching to socketaddr

---

protocol/timestamp.go
protocol/timestamp_test.go

Reduce the number of allocations in byteToTime, and use SO_TIMESTAMPING_NEW to make sure timestamps are always 64bit
unittests

Use SO_TIMESTAMPING_NEW and optimize byteToTime allocations

---

protocol/timestamp.go
protocol/timestamp_test.go
ptp4u/server/server.go
ptp4u/server/server_test.go
ptp4u/server/subscription.go
ptp4u/server/subscription_test.go
ptp4u/server/worker.go
ptp4u/server/worker_test.go
simpleclient/client.go

Use socket.Recvmsg everywhere. This allows us to avoid conversion to net.UDPConn which greatly reduces allocations and garbage delegations.
By using sockets everywhere it allows to simplify the code as well.
Notice the `UDPConn.ReadMsgUDP` ~0.87GiB and loadOrStore hack ~0.3GiB.
```
$ go tool pprof -alloc_space ~/heap.out
File: ptp4u
Build ID: 5670ad2fd454b86ca891ed96451e4d2d
Type: alloc_space
Time: Jul 31, 2021 at 5:33am (PDT)
Duration: 1.03mins, Total samples = 11.95GB
(pprof) top
Showing nodes accounting for 11610.01MB, 94.88% of 12236.12MB total
Dropped 13 nodes (cum <= 61.18MB)
Showing top 10 nodes out of 23
flat  flat%   sum%        cum   cum%
2916.81MB 23.84% 23.84%  3472.35MB 28.38% …
```

Use sockets instead of UDPConn for receive

---

ptp4u/server/server.go
ptp4u/server/server_test.go
ptp4u/server/subscription.go
ptp4u/server/subscription_test.go
ptp4u/server/worker.go

Delay response is a subscription. Clients must send a signalling request etc.
We were always treating it as an on demand request which was wasteful.
Already live

Make DelayResponse a proper subscription

---

protocol/timestamp.go

ParseSocketControlMessage is a very costly operation performed on every TX/RX HWTS packet.
It's performed against entire control buffer so having 128 bytes literally demands 2x allocations on heap.
Although we are yet to figure out how to improve/replace ParseSocketControlMessage it's clear we can save a lot by just parsing only needed amount of control buffer.
**(see the relative percentage, not the entire absolute values)**
```
$ go tool pprof -alloc_space ~/heap.out
File: ptp4u
Build ID: 574258b86ca02ad9c3fd94b4146fcb48
Type: alloc_space
Time: Aug 3, 2021 at 1:37pm (PDT)
Duration: 1mins, Total samples = 4.81GB
(pprof) top
Showing nodes accounting for 4.78GB, 99.31% of 4.81GB total
Dropped 34 nodes (cum <= 0.02GB) …
```

Tune control buffer size

---

protocol/timestamp.go
protocol/timestamp_test.go

Slash a large hot spot. The offset is constant on linux and project does not support other systems currently anyway.

Slash 10% of allocations by hardcoding socket control message offset

---

protocol/timestamp.go
ptpcheck/cmd/trace.go
simpleclient/client.go

In #17 we introduced great optimization by using `unix.Recvmsg` instead of `ReadMsgUDP`, but it requires setting socket to blocking mode, which we forgot to do in `simpleclient`.
Also on older kernels we might end up with `SO_TIMESTAMPING` messages even when asked for `SO_TIMESTAMPING_NEW`.
And finally, ptpcheck now has `-T` flag to manually select timestamping mode.
Local runs of `ptpcheck trace` in different modes

small fixes to timestamp.go and simpleclient after #17

---

phc/device.go

Close the file description and stop leaking open sockets.
`lsof` confirms we no longer leak sockets

close socket fd in phc.IfaceInfo

---

.circleci/config.yml
README.md
go.mod
go.sum
ziffy/README.md
ziffy/main.go
ziffy/node/config.go
ziffy/node/print.go
ziffy/node/print_test.go
ziffy/node/receiver.go
ziffy/node/receiver_test.go
ziffy/node/sender.go
ziffy/node/sender_test.go

This diff adds Ziffy, a CLI tool intended to triangulate datacenter switches that are not operating correctly as PTP TCs.
Unit tests; Tests between two internal hosts.

Add ziffy tool

---

ptp4u/server/server.go
ptp4u/server/worker.go
ptp4u/stats/json.go
ptp4u/stats/json_test.go
ptp4u/stats/stats.go
ptp4u/stats/stats_test.go

Hash is a great and powerful mechanism to evenly distribute all clients over the workers. However, we don't need all mighty of hash and in fact it's very expensive in allocations:
```
$ go tool pprof -alloc_objects ~/heap.out
File: ptp4u_oleg
Build ID: 76cd8b1a79251dee5c07210a4129e9b3
Type: alloc_objects
Time: Aug 28, 2021 at 2:32am (PDT)
Duration: 1mins, Total samples = 27398529
(pprof) top
Showing nodes accounting for 27393068, 100% of 27398529 total
Dropped 1 node (cum <= 136992)
Showing top 10 nodes out of 18
flat  flat%   sum%        cum   cum%
16273390 59.40% 59.40%   21008655 76.68%  third-party-source/go/golang.org/x/sys/unix.Recvmsg
4923693 17.97% 77.37%    4923693 17.97% …
```

Change way to select worker hash->rand.Seed

---

protocol/timestamp.go
ptp4u/server/worker.go

Probably the heaviest operation of the ptp4u is the sync/followup flow which requires reading of the TX timestamp.
While reading the `MSG_ERRQUEUE` we could not care less about socket address and other data except for oob.
So let's not allocate any resources. This diff fries approximately 10 Million (or 1GiB) of heap allocations per minute.
```
$ go tool pprof -alloc_objects ~/heap.out_hash
File: ptp4u
Build ID: 593f8c38a2075f87407dc5b4795b24d4
Type: alloc_objects
Time: Aug 29, 2021 at 2:11am (PDT)
Duration: 1mins, Total samples = 22946911
(pprof) top
Showing nodes accounting for 22943661, 100% of 22946911 total
Dropped 46 nodes (cum <= 114734)
Showing top 10 nodes out of 17
flat  flat%   sum%        cum   cum%
16624514 …
```

Add recvoob

---

ptp4u/main.go

Default for ptp client is 1h. Matching server as well.

Set max subscription duration to 1h

---

ptp4u/server/server.go
ptp4u/server/server_test.go
ptp4u/server/subscription.go
ptp4u/server/subscription_test.go
ptp4u/server/worker.go

Because the delayResp subscription is not an active one nothing terminates it when it legitimately expires.
But since we actually know the duration of the subscription we can simplify how we track subscriptions, remove redundant variable and reuse a lot of code.

Check subscription expiration

---

ziffy/main.go
ziffy/node/packets.go
ziffy/node/packets_test.go
ziffy/node/sender.go
ziffy/node/sender_test.go

While sending 'signaling' packets doesn't show TC, it's still useful to be able to trace with them in case this specific packet type is dropped along the way, while others pass.
tests pass
extensive manual testing shows the tool still works as expected

[ziffy] support sending signaling packets

---

protocol/timestamp.go
ptp4u/server/server.go

We used `hwtstampСonfig` with wrong int size, and it still somehow worked on Mellanox. Not so much with Broadcom:
```
failed to enable RX hardware timestamps: failed to run ioctl SIOCSHWTSTAMP: 34
```
This PR:
* fixed the int size of `hwtstampСonfig` fields
* added fallback to `HWTSTAMP_FILTER_PTP_V2_EVENT` in case the NIC doesn't support timestamping all packets.
* fixed failure logging in ptp4u server listener
ran ptp4u on Mellanox and Broadcom, tested against `ptpcheck trace`, all works as expected.

fix hw timestamp initialization

---

protocol/management_test.go
protocol/protocol.go
protocol/protocol_test.go
protocol/ptp4l.go
protocol/ptp4l_test.go

* Bump to protocol version 2.1
* Fix custom management TLV msg lengths
This change is a result of testing our code with latest ptp4l built from git master 2021-11-03, and allows the code to properly work with it.
The change is backwards compatible. I tested both ways:
* ptpcheck talking to both new and old ptp4l, both management proto and 'ptpcheck trace' which acts as a PTP client.
* ptp4l 3.1 works fine as a client for new ptp4u.

bump to IEEE 1588-2019 version, fix lengths for management packets

---

README.md
oscillatord/monitoring.go
oscillatord/monitoring_test.go
ptpcheck/cmd/oscillatord.go

* implementation of the monitoring protocol used by https://github.com/Orolia2s/oscillatord
* `ptpcheck oscillatord` subcommand to expose the data in human-readable and flat JSON form
unittests
human-readable
```
[root@timeserver ~]# ./ptpcheck oscillatord
Oscillator:
model: sa3x
fine_ctrl: 0
coarse_ctrl: 0
lock: false
temperature: 46.60C
GNSS:
fix: 3D (5)
fixOk: true
antenna_power: ON (1)
antenna_status: OPEN (4)
leap_second_change: NO WARNING (0)
leap_seconds: 18
```
json
```
[root@timeserver ~]# ./ptpcheck oscillatord --json
{"ptp.timecard.temperature":46,"ptp.timecard.lock":0,"ptp.timecard.gnss.fix_num":5,"ptp.timecard.gnss.fix_ok":1,"ptp.timecard.gnss.antenna_power":1,"ptp.timecard.gnss.antenna_status":4,"ptp.timecard.gnss.leap_second_change":0,"ptp.timecard.gnss.leap_seconds":18} …
```

Add oscillatord package and ptpcheck subcommand

---

protocol/timestamp.go
protocol/timestamp_test.go

`unix.Cmsghdr` used in `socketControlMessageTimestamp` has different size depending on the platform.
```
--- FAIL: TestSocketControlMessageTimestamp (0.00s)
timestamp_test.go:161: 
Error Trace:	timestamp_test.go:161
Error:      	Received unexpected error:
failed to find timestamp in socket control message
Test:       	TestSocketControlMessageTimestamp
```
amd64
```
> go test github.com/facebookincubator/ptp/protocol/... -run TestSocketControlMessageTimestamp -v
=== RUN   TestSocketControlMessageTimestamp
--- PASS: TestSocketControlMessageTimestamp (0.00s)
PASS
ok      github.com/facebookincubator/ptp/protocol       0.004s
```
386
```
> GOARCH=386 go test github.com/facebookincubator/ptp/protocol/... -run TestSocketControlMessageTimestamp -v
=== RUN   TestSocketControlMessageTimestamp
--- …
```

Fix TestSocketControlMessageTimestamp for platforms different from amd64
